before_script:
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=E:/dev/libraries -DCMAKE_PREFIX_PATH=E:/dev/boost_1_62_0 -DCMAKE_DEBUG_POSTFIX=_d -DWITH_JSON=OFF -DWITH_DCMTK=OFF -DWITH_LOGGING=OFF -DBUILD_EXAMPLES=OFF -DBUILD_WRAPPERS=OFF -DBUILD_INSTALL=ON -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF

cache:
  key: "%CI_BUILD_REF_NAME%"
  untracked: true
  paths:
    - build/
  
install-windows:
  stage: build
  script:
    - cmake --build . --config Release --target INSTALL
    - cmake --build . --config Debug --target INSTALL